spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/TWEETDB
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
  application:
    name: TWEET
  cloud:
    consul:
      enabled: false
      discovery:
        enabled: false
      config:
        enabled: false

server:
  port: 8080