spring: 
  datasource: 
    driverClassName: com.mysql.cj.jdbc.Driver 
    url: jdbc:mysql://localhost/TWEETDB
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
  application:
    name: TWEET
  cloud:
    consul:
      enabled: false
      discovery:
        enabled: false
      config:
        enabled: false
#      config:
#        enabled: true
#        prefix: config
#        defaultContext: application
#        data-key: data
#        profileSeperator: '::'
#        format: YAML


server:
  port: 8080
  

#cirtuit breaker name in program should be same as instance name here
#resilience4j:
#  circuitbreaker:
#    instances:
#      playerService:
#        failureRateThreshold: 50
#        ringBufferSizeInHalfOpenState: 3
#        waitDurationInOpenState: 30s
#        automaticTransitionFromOpenToHalfOpenEnabled: true
