DROP DATABASE IF EXISTS TWEETDB;
CREATE DATABASE TWEETDB;
USE TWEETDB;
CREATE TABLE TWEET(
	ID INT AUTO_INCREMENT PRIMARY KEY,
	MESSAGE VARCHAR(280) NOT NULL,
	USER_ID INT NOT NULL,
	CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

INSERT INTO TWEET(MESSAGE,USER_ID) VALUES('DUMMY TWEET 1',1);
INSERT INTO TWEET(MESSAGE,USER_ID) VALUES('DUMMY TWEET 2',3);
INSERT INTO TWEET(MESSAGE,USER_ID) VALUES('DUMMY TWEET 3',1);
INSERT INTO TWEET(MESSAGE,USER_ID) VALUES('DUMMY TWEET 4',2);
INSERT INTO TWEET(MESSAGE,USER_ID) VALUES('DUMMY TWEET 5',2);
INSERT INTO TWEET(MESSAGE,USER_ID) VALUES('DUMMY TWEET 6',4);

SELECT * FROM TWEET;


-- mentions table
CREATE TABLE MENTION(
	ID INT AUTO_INCREMENT PRIMARY KEY,
	TWEET_ID INT NOT NULL,
	USERNAME VARCHAR(15) NOT NULL
);
INSERT INTO MENTION VALUES(1,1,'@ashu');
INSERT INTO MENTION VALUES(2,3,'@yadav');
INSERT INTO MENTION VALUES(3,4,'@sachin');
INSERT INTO MENTION VALUES(4,5,'@agrim');


SELECT * FROM MENTION;


-- urls table
CREATE TABLE LINK(
	ID INT AUTO_INCREMENT PRIMARY KEY,
	TWEET_ID INT NOT NULL,
	URL VARCHAR(50) NOT NULL
);
INSERT INTO LINK VALUES(1,1,'linkedin.com');
INSERT INTO LINK VALUES(2,3,'google.com');
INSERT INTO LINK VALUES(3,4,'facebook.com');
INSERT INTO LINK VALUES(4,5,'instagram.com');
INSERT INTO LINK VALUES(5,3,'threads.com');


SELECT * FROM LINK;


-- hashtags table
CREATE TABLE HASHTAG(
	ID INT AUTO_INCREMENT PRIMARY KEY,
	TWEET_ID INT NOT NULL,
	TAG VARCHAR(50) NOT NULL
);
INSERT INTO HASHTAG VALUES(1,1,'#nature');
INSERT INTO HASHTAG VALUES(2,3,'#greatIndia');
INSERT INTO HASHTAG VALUES(3,4,'#webdevelopment');
INSERT INTO HASHTAG VALUES(4,5,'#love');
INSERT INTO HASHTAG VALUES(5,3,'#system');


SELECT * FROM HASHTAG;