spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/TWEET_FOLLOWING_AND_FOLLOWER?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  application:
    name: following-and-follower
  cloud:
    consul:
      enabled: false    # Keep false if Consul is not running
      discovery:
        enabled: false

server:
  port: 8082

# Resilience4j Circuit Breaker Config
resilience4j:
  circuitbreaker:
    instances:
      player-service:
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        sliding-window-size: 10
        wait-duration-in-open-state: 30s
        automatic-transition-from-open-to-half-open-enabled: true

# Custom Messages
player-service:
  messages:
    player-age: "Player didn't meet the age limit."
    sport-not-able-to-register: "Player Not Able To Register Due to Phone No."
    not-found: "Invalid RegisterId."

api:
  registration-success: "Player registered successfully with id"
