DROP DATABASE IF EXISTS TWEET_FOLLOWING_AND_FOLLOWER;
CREATE DATABASE TWEET_FOLLOWING_AND_FOLLOWER;
USE TWEET_FOLLOWING_AND_FOLLOWER;
-- FOLLOWING_AND_FOLLOWER table
CREATE TABLE FOLLOWING_AND_FOLLOWER(
	ID INT AUTO_INCREMENT PRIMARY KEY,
	FOLLOWING_ID INT NOT NULL,
	FOLLOWER_ID INT NOT NULL
);
INSERT INTO FOLLOWING_AND_FOLLOWER VALUES(1,1,2);
INSERT INTO FOLLOWING_AND_FOLLOWER VALUES(2,3,4);
INSERT INTO FOLLOWING_AND_FOLLOWER VALUES(3,4,5);
INSERT INTO FOLLOWING_AND_FOLLOWER VALUES(4,5,3);
INSERT INTO FOLLOWING_AND_FOLLOWER VALUES(5,1,3);


SELECT * FROM FOLLOWING_AND_FOLLOWER;