spring: 
  datasource: 
    driverClassName: com.mysql.cj.jdbc.Driver 
    url: jdbc:mysql://localhost/TWEET_MEDIA
    username: root
    password: root
  jpa: 
    hibernate.ddl-auto: update
  application:
    name: MEDIA
  cloud:
    consul:
      host: localhost
      discovery:
        hostname: localhost

server:
  port: 8081