DROP DATABASE IF EXISTS TWEET_MEDIA;
CREATE DATABASE TWEET_MEDIA;
USE TWEET_MEDIA;
-- urls table
CREATE TABLE MEDIA(
	ID INT AUTO_INCREMENT PRIMARY KEY,
	TWEET_ID INT NOT NULL,
	MEDIA_TYPE VARCHAR(100),
	URL VARCHAR(50) NOT NULL
);
INSERT INTO MEDIA VALUES(1,1,'VIDEO','linkedin.com');
INSERT INTO MEDIA VALUES(2,3,'VIDEO','google.com');
INSERT INTO MEDIA VALUES(3,4,'IMAGE','facebook.com');
INSERT INTO MEDIA VALUES(4,5,'GIF','instagram.com');
INSERT INTO MEDIA VALUES(5,1,'IMAGE','threads.com');


SELECT * FROM MEDIA;