DROP DATABASE IF EXISTS SEARCHDB;
CREATE DATABASE SEARCHDB;
USE SEARCHDB;
CREATE TABLE Search(
	id INT AUTO_INCREMENT PRIMARY KEY,
	dummy_name VARCHAR(280) NOT NULL
);

INSERT INTO Search(id,dummy_name) VALUES(1,'dummy1');
INSERT INTO Search(id,dummy_name) VALUES(2,'dummy2');


SELECT * FROM Search;